export const MJ_ACTIONS = ['BLEND', 'DESCRIBE', 'IMAGINE', 'INSIGHTFACE'];

export const MJ_BOTTYPES = ['MID_JOURNEY', 'NIJI_JOURNEY'];

export const MJ_VERSIONS = [
  { label: '6', value: '6' },
  { label: '5.2', value: '5.2' },
  { label: '5.1', value: '5.1' },
  { label: '5', value: '5' },
];

export const MJ_LIGHT = [
  { label: '自然光', value: 'Natural light' },
  { label: '阳光', value: 'Sun light' },
  { label: '暖光', value: 'Warm light' },
  { label: '冷光', value: 'Cold light' },
  { label: '情绪照明', value: 'Mood lighting' },
  { label: '明亮的', value: 'Bright' },
  { label: '柔和的照明/柔光', value: 'Soft illumination/soft lights' },
  { label: '荧光灯', value: 'Fluorescent lighting' },
  { label: '微光/晨光', value: 'Rays of shimmering light/morning light' },
  { label: '黄昏射线', value: 'Crepuscular Ray' },
  { label: '外太空观', value: 'Outer space view' },
  { label: '电影灯光/戏剧灯光', value: 'Cinematic lighting/dramatic lighting' },
  { label: '体积照明', value: 'Volumetric lighting' },
  { label: '双性照明', value: 'Bisexual lighting' },
  { label: '伦勃朗照明', value: 'Rembrandt Lighting' },
  { label: '分体照明', value: 'Split Lighting' },
  { label: '前灯', value: 'Front lighting' },
  { label: '背光照明', value: 'Back lighting' },
  { label: '干净的背景趋势', value: 'Clean background trending' },
  { label: '边缘灯', value: 'Rim lights' },
  { label: '全局照明', value: 'Global illuminations' },
  { label: '霓虹灯冷光', value: 'Neon cold lighting' },
  { label: '强光', value: 'Hard lighting' },
  { label: '斑驳光线', value: 'Dappled Light' },
  { label: '戏剧化灯光', value: 'Dramatic Lighting' },
  { label: '双重光源', value: 'Dual Lighting' },
  { label: '光斑', value: 'Flare' },
  { label: '闪光粉', value: 'Glitter' },
  { label: '日出 日落', value: 'Golden Hour' },
  { label: '强硬灯光', value: 'Hard Lighting' },
  { label: '夜店灯光', value: 'Nightclub Lighting' },
  { label: '彩虹火花', value: 'Rainbow Sparks' },
  { label: '星空', value: 'Starry' },
  { label: '薄雾', value: 'Misty foggy' },
  { label: '发射光', value: 'reflection light' },
];

export const MJ_VISUAL_ANGLES = [
  { label: '乌瞰图', value: "A bird's-eye view, aerial view" },
  { label: '俯视图', value: 'Top view' },
  { label: '倾斜移位', value: 'Tilt-shift' },
  { label: '卫星视图', value: 'Satellite view' },
  { label: '底视图', value: 'Bottom view' },
  { label: '主视图', value: 'Front view' },
  { label: '侧视图', value: 'side view' },
  { label: '后视图', value: 'rear view' },
  { label: '产品视图', value: 'Product view' },
  { label: '极端特写视图', value: 'Extreme closeup view' },
  { label: '仰视', value: 'Look up' },
  { label: '第一人称视角', value: 'First-person view' },
  { label: '等距视图', value: 'Isometric view' },
  { label: '特写视图', value: 'Closeup view' },
  { label: '高角度视图', value: 'High angle view' },
  { label: '微观', value: 'Microscopic view' },
  { label: '超侧角', value: 'Super side angle' },
  { label: '第三人称视角', value: 'Third-person perspective' },
  { label: '鸟瞰图', value: 'Aerial view' },
  { label: '两点透视', value: 'Two-point perspective' },
  { label: '三点透视', value: 'Three-point perspective' },
  { label: '立面透视', value: 'Elevation perspective' },
  { label: '横截面图', value: 'A cross-section view' },
];

export const MJ_SHOTS = [
  { label: '超广角镜头', value: 'Ultra wide shot' },
  { label: '电影镜头', value: 'Cinematic shot' },
  { label: '焦点对准', value: 'In focus' },
  { label: '景深(dof)', value: 'Depth of field (DOF)' },
  { label: '广角镜头相机型号', value: 'Canon 5D, 1Fujifilm XT100, Sony Alpha' },
  { label: '特写', value: 'Close-Up (CU)' },
  { label: '中特写', value: 'Medium Close-Up (MCU)' },
  { label: '中景', value: 'Medium Shot (MS)' },
  { label: '中远暴', value: 'Medium Long Shot (MLS)' },
  { label: '远景', value: 'Long Shot (LS)' },
  { label: '过肩景', value: 'Over the shoulder shot' },
  { label: '松散景', value: 'Loose shot' },
  { label: '近距离景', value: 'Tight shot' },
  {
    label: '两景(25)、三景(3S)、群景(GS)',
    value: 'Two shot (2S), three shot (3S), group shot (GS)',
  },
  { label: '风景照', value: 'Scenery shot' },
  { label: '背景虚化', value: 'Bokeh' },
  { label: '前景', value: 'Foreground' },
  { label: '背景', value: 'Background' },
  { label: '细节镜头(ECU)', value: 'Detail Shot (ECU)' },
];

export const MJ_CHARACTER_SHOTS = [
  { label: '肖像', value: 'Portrait' },
  { label: '全身照(FLS)', value: 'Full Length Shot (FLS)' },
  { label: '脸部特写', value: 'Face Shot (VCU)' },
  { label: '大特写', value: 'Big Close-Up (BCU)' },
  { label: '头部以上', value: 'Headshot' },
  { label: '胸部部以上', value: 'Chest Shot (MCU)' },
  { label: '腰部以上', value: 'Waist Shot (WS)' },
  { label: '膝盖以上', value: 'Knee Shot (KS)' },
  { label: '人占3/4', value: 'Long Shot (LS)' },
  { label: '人在远方', value: 'Extra Long Shot (ELS)' },
];

export const MJ_STYLES = [
  { label: '梦工厂影业', value: 'DreamWorks Pictures' },
  { label: '皮克斯', value: 'Pixar' },
  { label: '时尚', value: 'Fashion' },
  { label: '日本海报风格', value: 'Poster of Japanese graphic design' },
  { label: '90年代电视游戏', value: '90s video game' },
  { label: '法国艺术', value: 'French art' },
  { label: '包豪斯', value: 'Bauhaus' },
  { label: '日本动画片', value: 'Anime' },
  { label: '像素艺术', value: 'Pixel Art' },
  { label: '古典风，18-19世纪', value: 'Vintage' },
  { label: '乡村风格', value: 'Country style' },
  { label: '抽象风', value: 'Abstract' },
  { label: 'Riso印刷风', value: 'Risograph' },
  { label: '设计风', value: 'Graphic' },
  { label: '墨水渲染', value: 'Ink render' },
  { label: '民族艺术', value: 'Ethnic Art' },
  { label: '复古 黑暗', value: 'Retro dark vintage' },
  { label: '蒸汽朋克', value: 'Steampunk' },
  { label: '赛博朋克', value: 'Cyberpunk' },
  { label: '电影摄影风格', value: 'Film photography' },
  { label: '概念艺术', value: 'Concept art' },
  { label: '蒙太奇', value: 'Montage' },
  { label: '充满细节', value: 'Full details' },
  { label: '哥特式黑暗', value: 'Gothic gloomy' },
  { label: '写实主义', value: 'Realism' },
  { label: '黑白', value: 'Black and white' },
  { label: '统一创作', value: 'Unity Creations' },
  { label: '巴洛克时期', value: 'Baroque' },
  { label: '印象派', value: 'Impressionism' },
  { label: '新艺术风格', value: 'Art Nouveau' },
  { label: '洛可可风格', value: 'Rococo' },
  { label: '艾德里安·多诺休（油画）', value: 'Adrian Donohue' },
  { label: '艾德里安·托米尼（线性人物）', value: 'Adrian Tomine' },
  { label: '吉田明彦（厚涂人物）', value: 'Akihiko Yoshida' },
  { label: '鸟山明（七龙珠）', value: 'Akira Toiyama' },
  { label: '阿方斯·穆查（鲜艳线性）', value: 'Alphonse Mucha' },
  { label: '蔡国强（爆炸艺术）', value: 'Cai Guo-Qiang' },
  { label: '德鲁·斯特赞（星球大战）', value: 'Drew Struzan' },
  { label: '汉斯·阿尔普（达达主义、构成主义）', value: 'Hans Arp' },
  { label: '柔和人物', value: 'Ilya Kuvshiov' },
  { label: '梦幻流畅', value: 'James Jean' },
  { label: '美式人物', value: 'Jean Giraud' },
  { label: '局部解剖', value: 'Partial anatomy' },
  { label: '彩墨纸本', value: 'Color ink on paper' },
  { label: '涂鸦', value: 'Doodle' },
  { label: '伏尼契手稿', value: 'Voynich manuscript' },
  { label: '书页', value: 'Book page' },
  { label: '真实的', value: 'Realistic' },
  { label: '3D风格', value: '3D' },
  { label: '复杂的', value: 'Sophisticated' },
  { label: '真实感', value: 'Photoreal' },
  { label: '角色概念艺术', value: 'Character concept art' },
  { label: '文艺复兴', value: 'Renaissance' },
  { label: '野兽派', value: 'Fauvism' },
  { label: '立体派', value: 'Cubism' },
  { label: '抽象表现主义', value: 'Abstract Art' },
  { label: '超现实主义', value: 'Surrealism' },
  { label: '欧普艺术/光效应艺术', value: 'OP Art /Optical Art' },
  { label: '维多利亚时代', value: 'Victorian' },
  { label: '未来主义', value: 'Futuristic' },
  { label: '极简主义', value: 'Minimalist' },
  { label: '粗犷主义', value: 'Brutalist' },
  { label: '建构主义', value: 'Constructivist' },
  { label: '旷野之息', value: 'BOTW' },
  { label: '星际战甲', value: 'Warframe' },
  { label: '宝可梦', value: 'Pokémon' },
  { label: 'Apex英雄', value: 'APEX' },
  { label: '上古卷轴', value: 'The Elder Scrolls' },
  { label: '魂系游戏', value: 'From Software' },
  { label: '底特律:变人', value: 'Detroit: Become Human' },
  { label: '剑与远征', value: 'AFK Arena' },
  { label: '英雄联盟', value: 'League of Legends' },
  { label: '乔乔的奇异冒险', value: "Jojo's Bizarre Adventure" },
  { label: '新海诚', value: 'Makoto Shinkai' },
  { label: '副岛成记', value: 'Soejima Shigenori' },
  { label: '山田章博', value: 'Yamada Akihiro' },
  { label: '六七质', value: 'Munashichi' },
  { label: '水彩儿童插画', value: "Watercolor Children's Illustration" },
  { label: '吉卜力风格', value: 'Ghibli Studio' },
  { label: '彩色玻璃窗', value: 'Stained Glass Window' },
  { label: '水墨插图', value: 'Ink Illustration' },
  { label: '宫崎骏风格', value: 'Miyazaki Hayao Style' },
  { label: '梵高', value: 'Vincent Van Gogh' },
  { label: '达芬奇', value: 'Leonardo Da Vinci' },
  { label: '漫画', value: 'Manga' },
  { label: '点彩派', value: 'Pointillism' },
  { label: '伊藤润二（恐怖漫画风格）', value: 'Junji Ito' },
  { label: '手冢治虫', value: 'Qsamu Tezuka' },
  { label: '雷內·馬格利特（超现实主义风格）', value: 'Rene Magritte' },
  { label: '羅伯·岡薩爾維斯（奇幻、光学幻象风格）', value: 'Rob Gonsalves' },
  { label: '索爾·勒維特（几何概念艺术风格）', value: 'Sol LeWitt' },
  { label: '村田雄介（线条流畅、精美风格）', value: 'Yusuke Murata' },
  { label: '安东尼奥·莫拉', value: 'Antonio Mora' },
  { label: '新川洋司（细腻、机械设计风格）', value: 'Yoji Shinkawa' },
  { label: '国家地理', value: 'National Geographic' },
  { label: '超写实主义', value: 'Hyperrealism' },
  { label: '油画', value: 'Painting' },
  { label: '建筑素描', value: 'Architectural Sketching' },
  { label: '对称肖像', value: 'Symmetrical Portrait' },
  { label: '清晰的面部特征', value: 'Clear Facial Features' },
  { label: '室内设计', value: 'Interior Design' },
  { label: '武器设计', value: 'Weapon Design' },
  { label: '次表面散射', value: 'Subsurface Scattering' },
  { label: '游戏场景图', value: 'Game Scene Graph' },
  { label: '二次元', value: 'ACGN' },
  { label: '卡通', value: 'Cartoon' },
  { label: '童话风格', value: 'Fairy tale style' },
  { label: '卡通迷你风格', value: 'Chibi Anime Style' },
  { label: '动漫风格(恐怖题材)', value: 'J Horror Anime Style' },
  { label: '动漫风格(可爱、萌)', value: 'Kawaii Anime Style' },
  { label: '动漫风格(机器人)', value: 'Mecha Anime Style' },
  { label: '动漫风格(真实主义)', value: 'Realistic Anime Style' },
  { label: '动漫风格(带有动物耳朵和尾巴等特征)', value: 'Kemonomimi Anime Style' },
  { label: '山水画', value: 'Tradition Chinese Ink Painting' },
  { label: '浮世绘艺术', value: 'Ukiyo-e' },
  { label: '漫画风格', value: 'comics/manga' },
  { label: '库存插画风格', value: 'Stock illustration style' },
];

export const MJ_CAMERA_EFFECTS = [
  { label: '自拍、运动场景', value: 'GoPro' },
  { label: '佳能5D', value: 'Canon 5D' },
  { label: '富士XT100', value: 'Fujifilm XT100' },
  { label: '索尼Alpha', value: 'Sony Alpha' },
  { label: '无人机视角', value: 'Drone' },
  { label: '宝丽来', value: 'polaroid' },
  { label: '黑白照', value: 'black and white film' },
  { label: '柯达生产的彩色幻灯片底片', value: 'Kodachrome' },
  { label: '电影 8 毫米胶卷', value: 'shot on 8mm' },
  { label: '电影 16 毫米胶卷', value: 'shot on 16mm' },
  { label: '电影 35 毫米胶卷', value: 'shot on 35mm' },
  { label: '显微镜', value: 'Microscopic' },
  { label: '鱼眼镜头', value: 'Fisheye Lens' },
  { label: '广角镜头', value: 'Wide Angle' },
  { label: '超广镜头', value: 'Ultra-Wide Angle' },
  { label: '全景', value: 'Panorama' },
  { label: '短曝光', value: 'Short Exposure' },
  { label: '长曝光', value: 'Long Exposure' },
  { label: '双重曝光', value: 'Double Exposure' },
  { label: '2.8 光圈', value: 'f2.8' },
  { label: '柔焦', value: 'Soft Focus' },
  { label: '深焦', value: 'Deep Focus' },
  { label: '浅焦', value: 'Shallow Focus' },
  { label: '消失点', value: 'Vanishing Point' },
];

export const MJ_PAINTING_TYPES = [
  { label: '插画', value: 'Illustration' },

  { label: '油画', value: 'Oil painting' },
  { label: '摄影', value: 'Photography' },
  { label: '水彩', value: 'Watercolor' },
  { label: '素描', value: 'Sketch' },
  { label: '雕塑', value: 'Ink painting' },
  { label: '水墨画', value: 'Sculpture' },
  { label: '印刷版画', value: 'Blockprint' },
  { label: '相纸打印', value: 'Albument Print' },
  { label: '粉彩石膏雕塑', value: 'Chalkware' },
  { label: '彩铅素描', value: 'Color pencil sketch' },
  { label: '利诺剪裁', value: 'Lino cut' },
  { label: '手稿', value: 'Manuscript' },
  { label: '向量图', value: 'Vector' },
  { label: '丙烯画', value: 'Acrylic Painting' },
  { label: '16位图', value: '16 Bit' },
  { label: '8位图', value: '8 Bit' },
  { label: '3D打印', value: '3D Printed' },
];

export const MJ_RENDER_STYLE = [
  { label: '幻引擎', value: 'Unreal Engine' },
  { label: 'OC渲染', value: 'Octane Render' },
  { label: '渲染', value: 'Maxon Cinema 4D' },
  { label: '建筑渲染', value: 'Architectural Visualisation' },
  { label: '室内渲染', value: 'Corona Render' },
  { label: '真实感渲染', value: 'Quixel Megascans Render' },
  { label: 'V射线', value: 'V-Ray' },
];

export const MJ_SCENE = [
  { label: '天空之城', value: 'Castle in the Sky' },
  { label: '反乌托邦', value: 'Dystopia, anti-utopia' },
  { label: '幻想', value: 'Fantasy' },
  { label: '教室', value: 'Classroom' },
  { label: '异想天开', value: 'Whimsically' },
  { label: '卧室', value: 'Bedroom' },
  { label: '森林', value: 'Forest' },
  { label: '废墟', value: 'Ruins' },
  { label: '城市', value: 'City' },
  { label: '废弃城市建筑群', value: 'Deserted city buildings' },
  { label: '近未来都市', value: 'Near future city' },
  { label: '街景', value: 'Street scenery' },
  { label: '炼金室', value: 'Alchemy Laboratory' },
  { label: '宇宙', value: 'Universe I cosmos' },
  { label: '雨天', value: 'Rain' },
  { label: '在晨雾中', value: 'In the morning mist' },
  { label: '充满阳光', value: 'Full of sunlight' },
  { label: '银河', value: 'Galaxy' },
  { label: '黑暗地牢', value: 'Dungeon' },
  { label: '星云', value: 'Nebula' },
  { label: '疯狂麦斯沙地风格', value: 'Mad Max' },
  { label: '巴比伦空中花园', value: 'Hanging Gardens of Babylon' },
  { label: '草原草地', value: 'Meadow' },
  { label: '杂草丛生的', value: 'Overgrown nature' },
  { label: '后启示录、末日后', value: 'Post apocalyptic' },
];

export const MJ_IMAGE_ACCURACY = [
  {
    label: '高细节',
    value: 'High detail',
  },
  { label: '高品质', value: 'Hyper quality' },
  { label: '高分辨率', value: 'High resolution' },
  { label: '全高清.1080P', value: 'FHD 1080P' },
  { label: '2K', value: '2K' },
  { label: '4K', value: '4K' },
  { label: '8K', value: '8K' },
  { label: '8K流畅', value: '8K smooth' },
];
