name: '🐛 反馈缺陷'
description: '反馈一个问题缺陷'
labels: ['unconfirm']
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        在创建新的 Issue 之前，请先[搜索已有问题](https://github.com/lobehub/lobe-chat/issues)，如果发现已有类似的问题，请给它 **👍 点赞**，这样可以帮助我们更快地解决问题。  
        如果你在使用过程中遇到问题，可以尝试以下方式获取帮助：  
        - 在 [GitHub Discussions](https://github.com/lobehub/lobe-chat/discussions) 的版块发起讨论。  
        - 在 [LobeChat 社区](https://discord.gg/AYFPHvv2jT) 提问，与其他用户交流。 
  - type: dropdown
    attributes:
      label: '📦 部署环境'
      multiple: true
      options:
        - 'Official Preview'
        - 'Official Cloud'
        - 'Vercel'
        - 'Zeabur'
        - 'Sealos'
        - 'Netlify'
        - 'Docker'
        - 'Other'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: '📦 部署模式'
      multiple: true
      options:
        - '客户端模式(lobe-chat 镜像)'
        - '客户端 Pglite 模式(lobe-chat-pglite 镜像)'
        - '服务端模式(lobe-chat-database 镜像)'
    validations:
      required: true
  - type: input
    attributes:
      label: '📌 软件版本'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: '💻 系统环境'
      multiple: true
      options:
        - 'Windows'
        - 'macOS'
        - 'Ubuntu'
        - 'Other Linux'
        - 'iOS'
        - 'Android'
        - 'Other'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: '🌐 浏览器'
      multiple: true
      options:
        - 'Chrome'
        - 'Edge'
        - 'Safari'
        - 'Firefox'
        - 'Other'
    validations:
      required: true
  - type: textarea
    attributes:
      label: '🐛 问题描述'
      description: 请提供一个清晰且简洁的问题描述，若上述选项为`Other`，也请详细说明。
    validations:
      required: true
  - type: textarea
    attributes:
      label: '📷 复现步骤'
      description: 请提供一个清晰且简洁的描述，说明如何复现问题。
  - type: textarea
    attributes:
      label: '🚦 期望结果'
      description: 请提供一个清晰且简洁的描述，说明您期望发生什么。
  - type: textarea
    attributes:
      label: '📝 补充信息'
      description: 如果您的问题需要进一步说明，或者您遇到的问题无法在一个简单的示例中复现，请在这里添加更多信息。
